version:
    "3.8"
services:
    app:
        build: .
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        environment:
            - PORT=8000
            - NODE_ENV=development
        depends_on:
            - db
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=admin123
            - POSTGRES_USER=postgres
            - POSTGRES_DB=gorm

